### ISSUE TITLE
there is missing a function defination in demo_inpainting_lena_v2.m

### ISSUE THREAD

**Issue by PengJinHuang** [manyaafonso/Blind-Inpainting-l0-TV#1]
in the script **demo_inpainting_lena_v2.m**, there is missing a function defination named for **inpaintKSVD_v3**,i can't find it in this project, may i ask u where i can find it? thanks

**Comment by manyaafonso** [comment]
Hi, thanks for your interest in our work. The demo in demo_inpainting_lena_v2.m was to run a comparison with other methods, to share which we would need to ask permission from their authors, as they were shared privately. To run our method, I suggest you use the self contained demos or the newer python implementation https://github.com/manyaafonso/pySENS
